### ISSUE TITLE
Quantitative Scales API

### ISSUE THREAD

**Issue by anthonime** [gwtd3/gwt-d3#33]
LINEAR: (TEST CASE: TestLinearScale)
- [x] d3.scale.linear - construct a linear quantitative scale.
- [x] linear - get the range value corresponding to a given domain value.
- [x] linear.invert - get the domain value corresponding to a given range value.
- [x] linear.domain - get or set the scale's input domain.
- [x] linear.range - get or set the scale's output range.
- [x] linear.rangeRound - set the scale's output range, and enable rounding.
- [x] ~~linear.interpolate - get or set the scale's output interpolator.~~ (POSTPONED to #50 )
- [x] linear.clamp - enable or disable clamping of the output range.
- [x] linear.nice - extend the scale domain to nice round numbers.
- [x] linear.ticks - get representative values from the input domain.
- [x] linear.tickFormat - get a formatter for displaying tick values.
- [x] linear.copy - create a new scale from an existing scale.

SQRT / POW (TEST CASE: TestPowScale)
- [x] d3.scale.sqrt - construct a quantitative scale with a square root transform.
- [x] d3.scale.pow - construct a quantitative scale with an exponential transform.
- [x] pow - get the range value corresponding to a given domain value.
- [x] pow.invert - get the domain value corresponding to a given range value.
- [x] pow.domain - get or set the scale's input domain.
- [x] pow.range - get or set the scale's output range.
- [x] pow.rangeRound - set the scale's output range, and enable rounding.
- [x] ~~pow.interpolate - get or set the scale's output interpolator.~~ (POSTPONED to #50 )
- [x] pow.clamp - enable or disable clamping of the output range.
- [x] pow.nice - extend the scale domain to nice round numbers.
- [x] pow.ticks - get representative values from the input domain.
- [x] ~~pow.tickFormat - get a formatter for displaying tick values.~~ (BUGGED see #50)
- [x] pow.exponent - get or set the exponent power.
- [x] pow.copy - create a new scale from an existing scale.

LOG (TEST CASE: TestLogScale)
- [x] d3.scale.log - construct a quantitative scale with an logarithmic transform.
- [x] log - get the range value corresponding to a given domain value.
- [x] log.invert - get the domain value corresponding to a given range value.
- [x] log.domain - get or set the scale's input domain.
- [x] log.range - get or set the scale's output range.
- [x] log.rangeRound - set the scale's output range, and enable rounding.
- [x] ~~log.interpolate - get or set the scale's output interpolator.~~ (POSTPONED to #50 )
- [x] log.clamp - enable or disable clamping of the output range.
- [x] log.nice - extend the scale domain to nice powers of ten.
- [x] log.ticks - get representative values from the input domain.
- [x] ~~log.tickFormat - get a formatter for displaying tick values.~~ (BUGGED see #50)
- [x] log.copy - create a new scale from an existing scale.

QUANTIZE
- [x] d3.scale.quantize - construct a linear quantitative scale with a discrete output range.
- [x] quantize - get the range value corresponding to a given domain value.
- [x] ~~quantize.invertExtent - get the domain values for the specified range value.~~ POSTPONED to (#63)
- [x] quantize.domain - get or set the scale's input domain.
- [x] quantize.range - get or set the scale's output range (as discrete values).
- [x] quantize.copy - create a new scale from an existing scale.

THRESHOLD (TEST CASE: TestThresholdScale)
- [x] d3.scale.threshold - construct a threshold scale with a discrete output range.
- [x] threshold - get the range value corresponding to a given domain value.
- [x] ~~threshold.invertExtent - get the domain values for the specified range value.~~ POSTPONED to (#63)
- [x] threshold.domain - get or set the scale's input domain.
- [x] threshold.range - get or set the scale's output range (as discrete values).
- [x] threshold.copy - create a new scale from an existing scale.

QUANTILE (TEST CASE: TestQuantileScale)
- [x] d3.scale.quantile - construct a quantitative scale mapping to quantiles.
- [x] quantile - get the range value corresponding to a given domain value.
- [x] ~~quantile.invertExtent - get the domain values for the specified range value.~~ POSTPONED to (#63)
- [x] quantile.domain - get or set the scale's input domain (as discrete values).
- [x] quantile.range - get or set the scale's output range (as discrete values).
- [x] quantile.quantiles - get the scale's quantile bin thresholds.
- [x] quantile.copy - create a new scale from an existing scale.

IDENTITY (TEST CASE: TestIdentityScale)
- [x] d3.scale.identity - construct a linear identity scale.
- [x] identity - the identity function.
- [x] identity.invert - equivalent to identity; the identity function.
- [x] identity.domain - get or set the scale's domain and range.
- [x] identity.range - equivalent to identity.domain.
- [x] identity.ticks - get representative values from the domain.
- [x] identity.tickFormat - get a formatter for displaying tick values.
- [x] identity.copy - create a new scale from an existing scale.
